### ISSUE TITLE
Error: Can't create type index without a writable profile document

### ISSUE THREAD

**Issue by DougReeder** [NoelDeMartin/ramen#3]
I had just authorized the app, and clicked the button for "create cookbook"

Error details:
```
nR/t/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:104:16210
v@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:4153
r/j/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:5497
r/E/</<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:4578
cb@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2041
o@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2241
le/</<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2301
le/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2180
rR@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:104:16009
sR/t/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:112:1264
v@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:4153
r/j/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:5497
r/E/</<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:4578
cb@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2041
o@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2241
le/</<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2301
le/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:1:2180
oie@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:112:1105
createPrivate@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:116:72946
Qx/get/</<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:11:13245
u@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:11:12842
Qx/get/<@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:11:13218
createPrivateTypeIndex@https://ramen.noeldemartin.com/assets/index-f48f2c64.js:204:37754
findOrCreatePrivateTypeIndex@https://ramen.noeldemartin.c...
```

**Comment by NoelDeMartin** [comment]
Hi there, thanks for opening an issue!

This problem seems to be related with your identity provider, can you tell me which POD provider are you using? If you look at the [known issues](https://github.com/NoelDeMartin/ramen?tab=readme-ov-file#current-status-and-known-issues), you'll notice that there are some providers like `use.id` that have this problem. If there are more besides this one, I could add it to the list. And maybe I could improve the error message when it happens for known providers as well, to avoid the confusion.

**Comment by DougReeder** [comment]
I'm using an old account on inrupt.net.  I believe they use node-solid-server.

**Comment by NoelDeMartin** [comment]
I have tried with my `inrupt.net` account and it worked properly, so it may be some problem in your profile. Can you share your webId? If you don't want to share it publicly, you can send me an email (you can find my contact [in my website](https://noeldemartin.com)).

**Comment by NoelDeMartin** [comment]
I'm closing this given that it worked with `inrupt.net` on my side, feel free to reopen with more details if the problem persists.
